website/models.py
import ast
from website import db
from flask_login import UserMixin

class WebsiteUsers(db.Model, UserMixin):

    __tablename__ = "WebsiteUsers"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(200))
    password = db.Column(db.String(200))
    date_joined = db.Column(db.String(200))

website/forms.py
from flask_login import LoginManager
from wtforms import SubmitField, TextAreaField, StringField, validators, ValidationError
from flask_wtf import FlaskForm

class ContactForm(FlaskForm):
    "Create Form for e-mail contact"

    name = StringField("Name", [validators.data_required()])
    email = StringField("Email", [validators.data_required(), validators.Email()])
    subject = StringField("Subject", [validators.data_required()])
    message = TextAreaField("Message", [validators.data_required()])
    submit = SubmitField("Send")

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask import Flask, render_template, request, flash
from forms import ContactForm
from flask_mail import Message, Mail
from flask_login import LoginManager

db = SQLAlchemy()
app = Flask(__name__)

DB_NAME = "WebsiteUsers.db"

mail = Mail()

app.config["MAIL_SERVER"] = "smtp.web.de"
app.config["MAIL_PORT"] = 587
app.config["MAIL_USE_SSL"] = False
app.config["MAIL_USE_TLS"] = True
app.config["MAIL_USERNAME"] = 'johannes-hammacher@web.de'
app.config["MAIL_PASSWORD"] = 'weaponfreak'

mail.init_app(app)

def create_app():
    app.config['SESSION_TYPE'] = 'memcached'
    app.config['SECRET_KEY'] = 'super secret key'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'

    db.init_app(app)

    create_database(app)

    from website.views import views
    from website.auth import auth
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all(app=app)
            print('Created Database!')

website/auth.py
import datetime
import requests
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import pandas as pd

auth = Blueprint('auth',__name__)

@auth.route("/login", methods=["GET","POST"])
def login():
    return render_template("home.html")

website/main.py
from website import create_app

app = create_app()

if __name__ == '__main__':
    app.run(debug=True, port=7000)

website/views.py
import os.path
import json
from flask import jsonify,Blueprint, render_template, request,\
    flash, redirect, url_for, send_from_directory, Response, send_file,Markup, session
from flask_login import login_required, current_user
from website import db, mail
import plotly
from forms import ContactForm
from flask_mail import Message
from data_analysis import transportationDataVis

views = Blueprint('views', __name__)

@views.route("/", methods=["GET","POST"])
@views.route("/home", methods=["GET","POST"])
def home():
    return render_template("home.html")

@views.route("/education", methods=["GET","POST"])
def education():
    return render_template("edu.html")

@views.route("/projects", methods=["GET","POST"])
def projects():
    return render_template("projects.html")

@views.route("/contact", methods=["GET","POST"])
def contact():
    form = ContactForm()
    if request.method == 'POST':
        form.name = request.form['Name']
        form.subject = request.form['Subject']
        form.email = request.form['Email']
        form.message = request.form["Message"]

        if form.name != "" and form.subject != "" and form.email != "" and form.message != "":
            msg = Message(form.subject, sender="johannes-hammacher@web.de",
                          recipients=['johannes-hammacher@web.de'])
            msg.body = """
                              From: %s <%s>
                              %s
                              """ % (form.name, form.email, form.message)
            mail.send(msg)
            flash("Message sent successfully", category="success")
            return redirect(url_for("views.home"))
        else:
            flash('All fields are required.', category="error")
            return render_template('contact.html', form=form)
    elif request.method == 'GET':
        return render_template('contact.html', form=form)

@views.route("/dashboard_python",methods=["GET"])
def dashboard_python():
    figures = transportationDataVis("website/datasets/tfl-journeys-type.csv")
    line_plt = json.dumps(figures[0], cls=plotly.utils.PlotlyJSONEncoder)
    pie_chart = json.dumps(figures[1], cls=plotly.utils.PlotlyJSONEncoder)
    return render_template("Charts.html", line_plot=line_plt, pie_chart=pie_chart)

website/templates/Charts.html
{% extends "base.html" %} {% block title %}Transportation Data{% endblock %} {% block content
%}
<head>
<style>
h1 {text-align: center;}
</style>
</head>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
</head>

<style>
 body {
    padding-bottom: 100px;
}
</style>

<style>
  #intro {
    background-image: url('/static/Bild20.png');
    height: 100vh;
    width: 100vh;
    /* Background image is centered vertically and horizontally at all times */
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
    background-color: #464646;
    /* Font Colour */
    color:white;
  }

  #intro {
      position: fixed;
      top: 0;
      left: 0;

      /* Preserve aspet ratio */
      min-width: 100%;
      min-height: 100%;
    }
</style>


<html>
 <body>
  <h1>London Transportation Data - Line Plot</h1>
  <div id='chart1' class='chart'></div>
</body>
<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
<script type='text/javascript'>
  var graphs = {{line_plot | safe}};
  Plotly.plot('chart1',graphs,{});
</script>

 <body>
  <h1>London Transportation Data - Pie Chart</h1>
  <div id='chart2' class='chart'></div>
</body>
<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
<script type='text/javascript'>
  var graphs = {{pie_chart | safe}};
  Plotly.plot('chart2',graphs,{});
</script>
 <body>
<div class="container d-flex align-items-center justify-content-center text-center h-100">
          <div class="text-black">
            <h1 class="mb-3">More Projects</h1>
            <h5 class="mb-4">Go to the next Project or back to the overview</h5>
            <a class="btn btn-outline-dark btn-lg m-2 disabled" href="#" role="button">Dash (coming soon)</a>
              <a class="btn btn-outline-dark btn-lg m-2 disabled" href="#" role="button">R-Shiny (coming soon)</a>
            <a class="btn btn-outline-dark btn-lg m-2" href="/projects" role="button">Projects</a>
          </div>
</body>
<br>
<br>
</html>


{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
<style>
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: dark-grey;
   color: white;
   text-align: center;

}
</style>


  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/education">Education</a>
          <a class="nav-item nav-link" id="login" href="/projects">Projects</a>
          <a class="nav-item nav-link" id="signUp" href="/contact">Contact</a>
        </div>
      </div>
    </nav>
{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

  </header>

<div class="footer">
  <footer class="text-center text-lg-start text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Connect on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="https://www.linkedin.com/in/johannes-hammacher-090b97225/" class="me-4 link-grayish">
        <i class="fab fa-linkedin fa-3x"></i>
      </a>
      <a href="https://github.com/hami987" class="me-4 link-grayish">
        <i class="fab fa-github fa-3x"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->
  </footer>
</div>



</html>

website/templates/contact.html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
</head>

<style>
  #intro {
    background-image: url('/static/flight.jpg');
    height: 100vh;
    width: 100vh;
    /* Background image is centered vertically and horizontally at all times */
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
    background-color: #464646;
    /* Font Colour */
    color:white;
  }

  #intro {
      position: fixed;
      top: 0;
      left: 0;

      /* Preserve aspet ratio */
      min-width: 100%;
      min-height: 100%;
    }
</style>

<body>

    <div id="intro" class="bg-image shadow-2-strong">
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.8);">
        <div class="container d-flex align-items-center justify-content-center text-center h-100">
            <section id="contact" class="contact">
          <div class="text-white">
              <h1 class="mb-3">Contact me</h1>
              <h2 class="mb-3">Please fill out the form below, Thank you! </h2>
            <form action="{{ url_for('views.contact') }}" method=post>
                {{ form.csrf_token }}
                    <div class="form-group">
                      <label for="Email">Email</label>
                      <input type="email" id="Email" name="Email" class="form-control" placeholder="Email">
                    </div>
                  <div class="form-group">
                    <label for="Name">Name</label>
                    <input type="text" class="form-control" id="Name" name="Name" placeholder="XY Software Corp.">
                  </div>
                  <div class="form-group">
                      <label for="Subject">Subject</label>
                    <input type="text" class="form-control" id="Subject" name="Subject" placeholder="We´re Hiring!">
                  </div>
                    <div class="form-group">
                    <label for="Message">Message</label>
                    <textarea class="form-control" id="Message" name="Message" rows="3"></textarea>
                  </div>
                  <button type="submit" class="btn btn-primary">Send</button>

          </form>
          </div>
                <div class="text-white">
            <h1 class="mb-3">Further Links</h1>
            <h5 class="mb-4">Find the landing page, projects and education below</h5>
            <a class="btn btn-outline-light btn-lg m-2" href="/home" role="button">Home</a>
            <a class="btn btn-outline-light btn-lg m-2" href="/projects" role="button">Projects</a>
              <a class="btn btn-outline-light btn-lg m-2" href="/education" role="button">Education</a>
          </div>
            </section>
        </div>

    </div>
    </div>

</body>
<body>
{% extends "base.html" %} {% block title %}Contact{% endblock %} {% block content
%}

{% endblock %}
</body>

website/templates/edu.html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
</head>

<style>
  #intro {
    background-image: url('/static/duke.jpeg');
    height: 100vh;
    width: 100vh;
    /* Background image is centered vertically and horizontally at all times */
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
    background-color: #464646;
    /* Font Colour */
    color:white;
  }

  #intro {
      position: fixed;
      top: 0;
      left: 0;

      /* Preserve aspet ratio */
      min-width: 100%;
      min-height: 100%;
    }
</style>




<header>
    <div id="intro" class="bg-image shadow-2-strong">
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.8);">
        <div class="container d-flex align-items-center justify-content-center text-center h-100">
          <section id="resume" class="resume">
          <div class="container" data-aos="fade-up">

            <div class="section-title">
              <h2>Resume</h2>
              <p>Coming from a scientific background, curiosity and eagerness to learn define me. Apart from the formal education listed below, I have always searched ways to educate myself on various topics outside of University classes.</p>
            </div>

            <div class="row">
              <div class="col-lg-6">
                <h3 class="resume-title">Education</h3>
                <div class="resume-item">
                  <h4>Master of Science</h4>
                  <h5>2019 - Present</h5>
                  <p><em>Freie Universität Berlin</em></p>
                  <p>Specializing in Neurobiology and Computational Biology</p>
                    <p><em>Expected Graduation mark: 1.0</em></p>
                </div>
                  <div class="resume-item">
                  <h4>Exchange Program - Full Stipend</h4>
                  <h5>2021</h5>
                  <p><em>Duke University, NC, USA</em></p>
                  <p>Received a full stipend for one semester abroad to participate in Duke University´s Neurbiology PhD program.</p>
                </div>
                <div class="resume-item">
                  <h4>Bachelor of Science</h4>
                  <h5>2016 - 2019</h5>
                  <p><em>Freie Universität Berlin</em></p>
                  <p>Studied general Biology and later on focused on Neurobiology and Computational Biology.</p>
                    <p><em>Graduation mark: 1.8</em></p>
                </div>
              </div>
              <div class="col-lg-6">
                <h3 class="resume-title">Professional Experience</h3>
                <div class="resume-item">
                  <h4>Neurobiology Tutor</h4>
                  <h5>2017 - 2021</h5>
                  <p><em>Freie Universität Berlin</em></p>
                  <ul>
                      <p>Tutor for Biology Bachelor's students. Duties included preparation and execution of practical courses, teaching of neurobiological principles and proper scientific writing.</p>
                      <p>Duties also included visualization of experimental data using R and Python.</p>
                      <p>Furthermore, a custom built neuron-simulator based on a RaspberryPI and a graphical UI made in Python was used to teach students about the basics of neural signaling.</p>
                  </ul>
                </div>
                  <h3 class="resume-title">Tech Stack</h3>
                <div class="resume-item">
                  <ul>
                      <p>matplotlib, Tensorflow, PostgreSQL, Pandas, Numpy, pytorch, R-Shiny, Django, R, Flask, SQL, Git, Python</p>
                  </ul>
                </div>
              </div>
            </div>

          </div>
          <div class="text-white">
            <h1 class="mb-3">Further Links</h1>
            <h5 class="mb-4">Find the landing page and projects below</h5>
            <a class="btn btn-outline-light btn-lg m-2" href="/home" role="button">Home</a>
            <a class="btn btn-outline-light btn-lg m-2" href="/projects" role="button">Projects</a>
              <a class="btn btn-outline-light btn-lg m-2" href="/contact" role="button">Contact Me</a>
          </div>
        </section><!-- End Resume Section -->

          </div>
        </div>
    </div>

</header>
<body>
{% extends "base.html" %} {% block title %}Education{% endblock %} {% block content
%}

{% endblock %}
</body>

website/templates/home.html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
</head>

<style>
  #intro {
    background-image: url('/static/Bild20.png');
    height: 100vh;
    width: 100vh;
    /* Background image is centered vertically and horizontally at all times */
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
    background-color: #464646;
    /* Font Colour */
    color:white;
  }

  #intro {
      position: fixed;
      top: 0;
      left: 0;

      /* Preserve aspet ratio */
      min-width: 100%;
      min-height: 100%;
    }
</style>

<body>
    <title>Johannes Hammacher´s Website - Index</title>

    <!-- Background image -->
    <div id="intro" class="bg-image">
        <div class="container d-flex align-items-center justify-content-center text-center h-100">
          <div class="text-white">
            <h1 class="mb-3">Get to know me</h1>
            <h5 class="mb-4">Find my education path and projects below</h5>
            <a class="btn btn-outline-light btn-lg m-2" href="/education" role="button">Education</a>
            <a class="btn btn-outline-light btn-lg m-2" href="/projects" role="button">Projects</a>
              <a class="btn btn-outline-light btn-lg m-2" href="/contact" role="button">Contact Me</a>
          </div>
        </div>
    </div>
    <!-- Background image -->
</body>
<body>
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}

{% endblock %}
</body>

website/templates/home2.html
<!DOCTYPE html>
<html lang="en">

<style>
body {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

.container {
  display: flex;
  height: 100vh;
}

.bg-image {
  /* The image used */
  background-image: url("/static/code.jpg");

  /* Center and scale the image nicely */
  background-repeat: no-repeat;
  background-position: left top;
  background-size: 100% 100%;
  flex: 1;
  height: 100%;
}

.content {
  flex: 1;
  height: 100%;
  overflow: auto;
}

</style>

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<section class="container">
  <div class="bg-image">
  </div>
  <div class="content">
    <div class="container d-flex align-items-center justify-content-center text-center h-100">
          <div class="text-white">
            <h1 class="mb-3">Get to know me</h1>
            <h5 class="mb-4">Find my education path and projects below</h5>
            <a class="btn btn-outline-light btn-lg m-2" href="/education" role="button">Education</a>
            <a class="btn btn-outline-light btn-lg m-2" href="/projects" role="button">Projects</a>
              <a class="btn btn-outline-light btn-lg m-2" href="/contact" role="button">Contact Me</a>
          </div>
        </div>
  </div>

</section>

</body>


</html>

website/templates/projects.html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
</head>

<style>
  #intro {
    background-image: url('/static/code.jpg');
    height: 100vh;
    width: 100vh;
    /* Background image is centered vertically and horizontally at all times */
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
    background-color: #464646;
    /* Font Colour */
    color:white;
  }

  #intro {
      position: fixed;
      top: 0;
      left: 0;

      /* Preserve aspet ratio */
      min-width: 100%;
      min-height: 100%;
    }
</style>




<header>
    <!-- Background image -->
    <div id="intro" class="bg-image">
        <div class="container d-flex align-items-center justify-content-center text-center h-100">
          <div class="text-white">
            <h1 class="mb-3">Dashboards</h1>
            <h5 class="mb-4">Click on the links below to see the individual dashboards</h5>
            <a class="btn btn-outline-light btn-lg m-2" href={{url_for("views.dashboard_python")}} role="button">Python+Plotly+HTML</a>
            <a class="btn btn-outline-light btn-lg m-2 disabled" href="#" role="button">Dash (coming soon)</a>
              <a class="btn btn-outline-light btn-lg m-2 disabled"href="#" role="button">R-Shiny (coming soon)</a>
          </div>
        </div>
    </div>
    <!-- Background image -->
</header>
<body>
{% extends "base.html" %} {% block title %}Projects{% endblock %} {% block content
%}

{% endblock %}
</body>